spring:
  application:
    name: ${APP_NAME:client-service}

server:
  address: ${ADDRESS:0.0.0.0}
  port: ${PORT:8001}

food-ordering:
  address: ${ORDERING_ADDRESS:localhost}
  port: ${ORDERING_PORT:8002}

client-service:
  clients: ${CLIENT_COUNT:10}
  time-unit: ${TIME_UNIT:1}
  time-duration: ${TIME_DURATION:100}